### ISSUE TITLE
Receive spawn UNKNOWN in windows-latest

### ISSUE THREAD

**Issue by JonasJacobsUserspace** [EndBug/add-and-commit#33]
## Error
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at Object.execFile (child_process.js:224:17)
    at Object.131 (D:\a\_actions\EndBug\add-and-commit\v4\lib\index.js:1:592)
    at __webpack_require__ (D:\a\_actions\EndBug\add-and-commit\v4\lib\index.js:1:154)
    at startup (D:\a\_actions\EndBug\add-and-commit\v4\lib\index.js:1:291)
    at module.exports.87 (D:\a\_actions\EndBug\add-and-commit\v4\lib\index.js:1:323)
    at Object.<anonymous> (D:\a\_actions\EndBug\add-and-commit\v4\lib\index.js:1:333)
##[error]spawn UNKNOWN
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) {
  errno: 'UNKNOWN',
  code: 'UNKNOWN',
  syscall: 'spawn'

## The following system:
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20200630.0

**Comment by EndBug** [comment]
Hi, thanks for the issue!
I've pushed some changes to the master branch, it would be awesome if you could test them in your workflow, using the `EndBug/add-and-commit@master` name. If they are fine I'll publish a patch with them.

### Known issues:
Logs from the child process don't show in the action logs: I don't know how to fix it, I'll open an issue later about that.

**Comment by JonasJacobsUserspace** [comment]
Thanks for the quick reply, I have tested it with the new changed in master and commit is working in windows.

**Comment by EndBug** [comment]
Perfect! I'll publish the fix in `v4.2.1` (you can also use `v4` and `latest`)

@all-contributors please add @JonasJacobsUserspace for bug

**Comment by EndBug** [comment]
The new version has been published, thanks for your issue 🎉
