### ISSUE TITLE
Error while using this github action (ErrorEXError [JSONError]: Unexpected token)

### ISSUE THREAD

**Issue by mys2kor** [EndBug/add-and-commit#433]
I am trying to use this action in my private repo but I run into an error like below during the execution of the workflow. The error is very long. Here I am providing the gist of it.

![grafik](https://user-images.githubusercontent.com/109787441/190385265-e08da8e3-bb45-4dfe-80f8-d0546811850e.png)

The end of the error is like so
```
ErrorEXError [JSONError]: Unexpected token } in JSON at position 142 while parsing near '...ear --port 8000",  },  "devDependencie...' in package.json
    at e.exports (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:82368)
    at parse (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:51821)
    at Function.e.exports.sync (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:51924)
    at Function.sync (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:83199)
    at Signale.get packageConfiguration [as packageConfiguration] (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:116193)
    at new Signale (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:115057)
    at Object.528 (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:88739)
    at __nccwpck_require__ (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:517248)
    at Object.5140 (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:1:142510)
    at __nccwpck_require__ (/home/runner/work/_actions/EndBug/add-and-commit/v9/lib/index.js:7:517248) {
  fileName: 'package.json'
}
```

Can you please let me know how to get this working? Thanks.

**Comment by EndBug** [comment]
Hi, can you send the workflow file and the complete log of the step that uses my action?

**Comment by martijnarts** [comment]
Hi @mys2kor, could you share how you solved this issue?

**Comment by mys2kor** [comment]
@martijnarts I ended up adding the below code directly to my GitHub action
```
      - name: Commit created HTML & Push changes
        run: |
          apt-get update && apt-get install git
          git remote set-url origin "https://github.com/<repo you want the push to be done>"
          git config --global user.name "${{github.actor}}"
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git add .
          git commit -m "<Commit message that we want>'"
          git push https://${{secrets.PAT}}@github.com/<repo you want the push to be done>
```
I my case, I use a Linux runner for this github actions. Also, I just create 1 file (that too in the action itself) and then I want to commit & push it so `git add .`  works just fine. If you want to control precisely (add & commit a specific file for example), the nyou may want to tinker with the code above.

**Comment by martijnarts** [comment]
@EndBug fwiw it looks like the action reads and validates a `package.json` in the workdir if there is one?

**Comment by martijnarts** [comment]
my `package.json` was invalid (extra comma somewhere), fixing it stopped this bug from happening.

**Comment by EndBug** [comment]
>  it looks like the action reads and validates a `package.json` in the workdir if there is one?

Hmm, this is weird...
Maybe one of the dependencies reads it to get more info, but I have no idea why or which one is doing that...
